### PR TITLE
Add single localized upload nonce.

### LINKED ISSUE #270: Nonce Error for Authenticated Users
Seeing sparse reports of a "Nonce Error" with the Uploads field with Authenticated Users.

---

Reference: https://wpninjas.kustomerapp.com/app/customers/596c4ad79236fa00114676c5/event/59757b37291ce90011c789f2

### PR DESCRIPTION
**Pull request by kjohnson**
As an interim step to resolving the expired nonce issue in Save Progress, I suggest that we move to a single upload nonce which is localized with the form display as opposed to storing the nonce in the field data.

Closes #270.

### CODE REVIEW

**Comment by polevaultweb** [comment]
@kjohnson this will revert https://github.com/wpninjas/ninja-forms-uploads/pull/244 which was introduced for added security. I'd rather keep to one nonce per field.

How much more work will it be to whitelist field model settings from being loaded by Save Progress?

cc @kstover

**Comment by kjohnson** [comment]
@polevaultweb whitlisting/blacklisting the attributes wouldn't resolve the conflict, rather we would need to move the nonce values to the form settings.

**Comment by polevaultweb** [comment]
@kjohnson I'm not sure I fully understand. Is there no way to tell Save Progress to load all field settings for the model except a certain setting, and instead load that as normal? cc @kstover

**Comment by kjohnson** [comment]
@polevaultweb Save Progress resets the Fields Collection, so it is a full swap of data.

**Pull request closed without merging**
